import argparse
import datetime
import math
import sys
import gzip
from collections import defaultdict

parser = argparse.ArgumentParser(description = 'Convert Beagle genotype likelihoods (GL) file to VCF format')

parser.add_argument('beaglefile', help='INPUT: name of gzipped Beagle GL file for one chromosome(e.g. angsdput.beagle generated by angsd)')
parser.add_argument('chrom', help='chromosome number')
parser.add_argument('vcffile', help='OUTPUT: name of VCF file to output to')

args = parser.parse_args()
thischrom = args.chrom

allele_key = {'0':'A', '1':'C', '2':'G', '3':'T'}

with open("/global/home/users/deboraycb/scratch/atahualpa/data/ref/human_g1k_v37.fasta.bgz.fai", "r") as fai:
    for line in fai:
        c,clen = line.strip().split()[:2]
        if c == thischrom:
            break

outfh = open(args.vcffile, 'w')
outfh.write('##fileformat=VCFv4.2\n')
now=datetime.datetime.now()
outfh.write('##fileDate={}{:02}{:02}\n'.format(now.year,now.month,now.day))
outfh.write('##source=beagle2vcf.py\n')   
outfh.write('##reference=/global/home/users/deboraycb/scratch/atahualpa/data/ref/human_g1k_v37.fasta.bgz\n')
outfh.write('##FILTER=<ID=PASS,Description="All filters passed">\n')
outfh.write('##FORMAT=<ID=GL,Number=G,Type=Float,Description="three log10-scaled likelihoods for RR,RA,AA genotypes, angsd GL=0 was converted to -7">\n')
outfh.write('##INFO=<ID=INDEL,Number=0,Type=Flag,Description=\"\">\n')
outfh.write('##contig=<ID='+thischrom+',length='+clen+'>\n')

with gzip.open(args.beaglefile, 'r') as infh:
    header = infh.readline()
    samples = ['atahualpa'+x.decode("utf-8") for x in header.strip().split()[3::3]]
    outfh.write('\t'.join(['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT']+samples)+'\n') 
    for line in infh:
        fields = [x.decode("utf-8") for x in line.split()]
        crpos=fields[0]
        chrom,pos = fields[0].split('_')
        ref = allele_key[fields[1]]
        alt = allele_key[fields[2]]
        log10GL = ['{:.7f}'.format(math.log10(float(x))) if float(x)!=0 else '-7' for x in fields[3:]]   
        GLs = [','.join(x) for x in zip(log10GL[0::3], log10GL[1::3], log10GL[2::3])]
        newline = [chrom, pos, fields[0], ref, alt, '.', 'PASS', '.', 'GL']+GLs
        outfh.write('\t'.join(newline)+'\n')
outfh.close()
